# Generated by Django 4.2.5 on 2023-09-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
