# Generated by Django 4.2.5 on 2023-09-21 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('tipo_usuario', models.CharField(choices=[('cliente', 'Cliente'), ('funcionario', 'Funcionario')], default='cliente', max_length=100, verbose_name='Tipo de Usuário')),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
    ]
